//
// Created by Simone on 09/11/22.
//

#ifndef ELOQUENTESP32CAM_DEFINES_H
#define ELOQUENTESP32CAM_DEFINES_H

#if defined(MAX_RESOLUTION_96x96)
#define MAX_RESOLUTION_WIDTH 96
#define MAX_RESOLUTION_HEIGHT 96
#elif defined(MAX_RESOLUTION_160x120) || defined(MAX_RESOLUTION_QQVGA)
#define MAX_RESOLUTION_WIDTH 160
#define MAX_RESOLUTION_HEIGHT 120
#elif defined(MAX_RESOLUTION_176x144)
#define MAX_RESOLUTION_WIDTH 176
#define MAX_RESOLUTION_HEIGHT 144
#elif defined(MAX_RESOLUTION_320x240) || defined(MAX_RESOLUTION_QVGA)
#define MAX_RESOLUTION_WIDTH 320
#define MAX_RESOLUTION_HEIGHT 240
#elif defined(MAX_RESOLUTION_480x320)
#define MAX_RESOLUTION_WIDTH 480
#define MAX_RESOLUTION_HEIGHT 320
#elif defined(MAX_RESOLUTION_640x480) || defined(MAX_RESOLUTION_VGA)
#define MAX_RESOLUTION_WIDTH 640
#define MAX_RESOLUTION_HEIGHT 480
#elif defined(MAX_RESOLUTION_800x600)
#define MAX_RESOLUTION_WIDTH 800
#define MAX_RESOLUTION_HEIGHT 600
#elif defined(MAX_RESOLUTION_1024x768) || defined(MAX_RESOLUTION_XGA)
#define MAX_RESOLUTION_WIDTH 1024
#define MAX_RESOLUTION_HEIGHT 768
#elif defined(MAX_RESOLUTION_1280x720) || defined(MAX_RESOLUTION_HD)
#define MAX_RESOLUTION_WIDTH 1280
#define MAX_RESOLUTION_HEIGHT 720
#elif defined(MAX_RESOLUTION_1280x1024)  || defined(MAX_RESOLUTION_SXGA)
#define MAX_RESOLUTION_WIDTH 1280
#define MAX_RESOLUTION_HEIGHT 1024
#elif defined(MAX_RESOLUTION_1600x1200) || defined(MAX_RESOLUTION_UXGA)
#define MAX_RESOLUTION_WIDTH 1600
#define MAX_RESOLUTION_HEIGHT 1200
#endif

// default width
#ifndef MAX_RESOLUTION_WIDTH
#define MAX_RESOLUTION_WIDTH 1280
#endif

// default height
#ifndef MAX_RESOLUTION_HEIGHT
#define MAX_RESOLUTION_HEIGHT 720
#endif

#endif //ELOQUENTESP32CAM_DEFINES_H
